### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by tututututututu** [allenymt/PrivacySentry#10]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'.
> Invalid opcode 169

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:stripDebugDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by tututututututu** [comment]
对NDK版本 是什么要求

**Comment by allenymt** [comment]
NDK版本没有要求，建议检查下本地配置
