### ISSUE TITLE
运行app提示:  disable print file

### ISSUE THREAD

**Issue by August1993** [allenymt/PrivacySentry#106]
![image](https://github.com/allenymt/PrivacySentry/assets/37497852/86912b4b-4b69-499f-abbb-cbe0ad88637e)

大佬你好. 集成sdk后,运行项目,会提示 disable print file,这个是什么原因呢
手机系统:Android 13

**Comment by August1993** [comment]
集成框架后,app内部获取版本号, Android Id的方法 就都失效了,全部为空,    移除框架,这些属性又都能获取到了

**Comment by allenymt** [comment]
初始化的代码看看

**Comment by allenymt** [comment]
在隐私协议确认的时候调用，这一步非常重要！，一定要加
    kotlin:PrivacySentry.Privacy.updatePrivacyShow()
    java:PrivacySentry.Privacy.INSTANCE.updatePrivacyShow();

这一步加了吗？

**Comment by August1993** [comment]
升级了框架,且加上这句代码:PrivacySentry.Privacy.INSTANCE.updatePrivacyShow();   现在可以获取到属性了,但是隐私文件好像没有生成

**Comment by allenymt** [comment]
每隔一分钟才会写入文件
