### ISSUE TITLE
无法引入包体了

### ISSUE THREAD

**Issue by crazyzjw** [allenymt/PrivacySentry#108]
<img width="1200" alt="image" src="https://github.com/allenymt/PrivacySentry/assets/12543049/00c57ff6-cf31-4c51-9f21-06bd118a88f6">

**Comment by yanshengqi** [comment]
解决了吗

**Comment by allenymt** [comment]
maven { url 'https://jitpack.io' } 这个配置了吗？ 看报错日志都没有jitpack的

**Comment by crazyzjw** [comment]
> 

配置了也不行  - -尴尬

**Comment by allenymt** [comment]
配置了报什么错

**Comment by crazyzjw** [comment]
> maven { url 'https://jitpack.io' }

这个一直都有配置的。报错就是截图的。

**Comment by allenymt** [comment]
1. 在根目录的build.gralde下添加
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
	
	buildscript {
	     dependencies {
	         // 添加插件依赖
	         classpath 'com.github.allenymt.PrivacySentry:plugin-sentry:1.2.7'
	     }
	}
	
	allprojects {
        repositories {
            maven { url 'https://jitpack.io' }
        }
    }

gradle插件的依赖仓库也加了吧，

**Comment by allenymt** [comment]
建议检查下网络，代理吧，我这边试了1.2.7可以的
