### ISSUE TITLE
gradle依赖加入不了

### ISSUE THREAD

**Issue by fengmingye** [allenymt/PrivacySentry#11]
gradlew依赖加入不了：
在项目build.gradle中
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        //classpath 'io.fabric.tools:gradle:1.25.4'
        classpath 'com.meituan.android.walle:plugin:1.1.6'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//        classpath 'com.github.allenymt:PrivacySentry:0.0.7'
        classpath 'com.github.allenymt.PrivacySentry:plugin-sentry:1.0.2'
    }

报错：

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.allenymt.PrivacySentry:plugin-sentry:1.0.2.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.pom
       - https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.jar
       - https://dl.google.com/dl/android/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.pom
       - https://dl.google.com/dl/android/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.jar
       - https://repo.maven.apache.org/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.pom
       - https://repo.maven.apache.org/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.jar
       - https://maven.fabric.io/public/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.pom
       - https://maven.fabric.io/public/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.2/plugin-sentry-1.0.2.jar
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by allenymt** [comment]
在根目录的build.gralde下添加
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
