### ISSUE TITLE
there was an error calling PrivacyTelephonyProxy$TelephonyProxy.getSimState

### ISSUE THREAD

**Issue by topcloud-xx** [allenymt/PrivacySentry#116]
小米手机
MIUI 13.0.6
Android 12
还用PrivacySentry1.3.3版本会出现以下错误，造成app闪退
AndroidRuntime: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
AndroidRuntime: at com.yl.lib.privacy_proxy.PrivacyTelephonyProxy$TelephonyProxy.getSimState(PrivacyTelephonyProxy.kt:422)

降级到PrivacySentry1.3.2、PrivacySentry1.3.1版本后，则正常。对比了PrivacyTelephonyProxy的getSimState没有发现有差异。
不知道会是什么原因。

**Comment by allenymt** [comment]
详细的问题堆栈有吗？

**Comment by allenymt** [comment]
1.3.4已修复
