### ISSUE TITLE
这种方案对于那种第三方sdk 动态下载的插件，插件中调用了敏感api是否也能够检测到呢？

### ISSUE THREAD

**Issue by liu1912009189** [allenymt/PrivacySentry#12]

**Comment by liu1912009189** [comment]
目测，目前所有的Android 插桩方案都是编译时插桩，不管时通过gradle相关的api,查找对应的字节码，然后通过ASM修改字节码，还是AspectJ，都是在编译时。对于App运行时下载的插件，插件里的敏感api调用，就无法检测了，因为错过了插桩的时机。所以想请问哈，你这种方案是否能解决这种问题？

**Comment by allenymt** [comment]
动态下载的检测不到的

**Comment by allenymt** [comment]
你这个在运行时hook了，可以用大佬的 https://github.com/tiann/epic
