### ISSUE TITLE
小白：请问如何使用？

### ISSUE THREAD

**Issue by TBOsec** [allenymt/PrivacySentry#13]
# **已经编译成app，请问如何使用？ 如何实现检测其它app的采集行为。**
![image](https://user-images.githubusercontent.com/24735925/156728265-48760863-496a-40fa-9814-26930303549e.png)

**Comment by allenymt** [comment]
额，文档里有写的。插件引用下就行

**Comment by TBOsec** [comment]
也就是说，只能检测自身开发的app，无法检测已经打包成apk的应用，对吗？
