### ISSUE TITLE
添加该插件后编译不过

### ISSUE THREAD

**Issue by 857288218** [allenymt/PrivacySentry#16]
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalProdRelease'.
> Could not resolve all dependencies for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not determine artifacts for com.github.allenymt.PrivacySentry:hook-sentry:1.0.2: Skipped due to earlier error

**Comment by 857288218** [comment]
库下载不来了？

**Comment by allenymt** [comment]
maven { url 'https://jitpack.io' }  , 可能要挂代理
