### ISSUE TITLE
自建代理类出错

### ISSUE THREAD

**Issue by JiayuanChan** [allenymt/PrivacySentry#17]
你好，项目原因，需要自建代理类，故使用时，不引用 implementation 'com.github.allenymt.PrivacySentry:privacy-proxy:1.0.3'，而是直接将 privacy-proxy 的源码拷贝到项目中，并作修改。当app运行时报如下错误：
![image](https://user-images.githubusercontent.com/18372409/160854683-3fb96ca5-c475-4642-a8ea-6f84d46fa5f8.png)
请问该如何解决！

**Comment by allenymt** [comment]
自建的代理类是不是被混淆了？

**Comment by JiayuanChan** [comment]
嗯嗯，是的，代码被混淆，已解决！
