### ISSUE TITLE
defaultConfigHookBuilder 是私有的，我不知该怎么调用。

### ISSUE THREAD

**Issue by tongshendota** [allenymt/PrivacySentry#2]
private fun defaultConfigHookBuilder(builder: PrivacySentryBuilder): PrivacySentryBuilder {
            builder?.configHook(defaultAmsHook(builder!!))
                ?.configHook(defaultPmsHook(builder!!))
                ?.configHook(defaultTmsHook(builder!!))
                ?.configHook(defaultCmsHook(builder!!))
            return builder
        }

我初始化报错，然后我修改成这样了。
        PrivacySentry.Privacy.INSTANCE.init(this,
                Objects.requireNonNull(PrivacySentry.Privacy.INSTANCE.getBuilder())
                        .configHook(PrivacySentry.Privacy.INSTANCE.defaultAmsHook(builder))
                        .configHook(PrivacySentry.Privacy.INSTANCE.defaultPmsHook(builder))
                        .configHook(PrivacySentry.Privacy.INSTANCE.defaultTmsHook(builder))
                        .configHook(PrivacySentry.Privacy.INSTANCE.defaultCmsHook(builder)));

**Comment by allenymt** [comment]
README.md 已修改，建议用configPrivacyType(PrivacySentryBuilder.PrivacyType.TRANSFORM)吧，这样就不需要调用defaultConfigHookBuilder 去hook 系统服务了。

后面的版本会放弃hook系统服务的方案，全量切换到transform的方案
