### ISSUE TITLE
调用了getExternalFilesDir

### ISSUE THREAD

**Issue by yangdong-wuye** [allenymt/PrivacySentry#21]
写入日志的时候调用了getExternalFilesDir函数，华为审核不给过

**Comment by allenymt** [comment]
线上不要把写file打开，会影响性能，这块我没做过处理，都是在主线程写文件的，初始化的时候enableFileResult设置为false

**Comment by yangdong-wuye** [comment]
> 线上不要把写file打开，会影响性能，这块我没做过处理，都是在主线程写文件的，初始化的时候enableFileResult设置为false

好的，谢谢大佬。另外我想用这个库做一个react-native版本的，可以吗大佬？

**Comment by allenymt** [comment]
没明白，这个rn有什么关系
