### ISSUE TITLE
集成到项目 用到openinstall时编译报错

### ISSUE THREAD

**Issue by dogTowolfs** [allenymt/PrivacySentry#24]
项目有openinstall时编译报错，openinstall是大众三方，有时间看看吧

deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/i/f.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/e.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/f$a.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/f.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/g$a.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/g$b.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/g.class
deal with jar file is: /Users/tianniu/Documents/mayagit/chinads-android/app/build/intermediates/transforms/PrivacyCollectTransform/debug/1.jar.absolutePath entryName is io/openinstall/h.class
:app:transformClassesWithPrivacySentryPluginForDebug (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 1.781 secs.
AAPT2 aapt2-4.2.0-7147631-osx Daemon #0: shutdown

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'.
> java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0

**Comment by allenymt** [comment]
openinstall是开源的吗？ 库地址发来看看

**Comment by allenymt** [comment]
可以先参考readme.md 根据包名加黑名单

**Comment by allenymt** [comment]
// 试了下，应该跟asm版本有冲突，先加黑名单
privacy {
    // 设置免hook的黑名单，可以先加黑
    blackList = ["io.openinstall.sdk"]
}
