### ISSUE TITLE
SHA-256 digest error for META-INF/versions/11

### ISSUE THREAD

**Issue by yangjieK** [allenymt/PrivacySentry#36]
环境
classpath 'com.github.allenymt.PrivacySentry:plugin-sentry:1.0.5' 
gradle 6.7.1
java 11

编译异常

Execution failed for task ':app:transformClassesWithPrivacyCollectTransformForScreen_touch_wwa_zediel_Release'.
> java.lang.SecurityException: SHA-256 digest error for META-INF/versions/11/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyFactorySpi$X448.class

**Comment by zhaolinggang** [comment]
SHA-256 digest error for org/eclipse/paho/client/mqttv3/internal/ClientState.clas求救，在接入插件的时候报这个错。

**Comment by runforprogram** [comment]
> SHA-256 digest error for org/eclipse/paho/client/mqttv3/internal/ClientState.clas求救，在接入插件的时候报这个错。

这个好像是因为mqttv3这个库加密了，解压后再压缩回去报错 使用 `jarsigner -verify` path/mqttv3 jar 会显示已验证，可以在自己改下代码，在遍历的时候排除这个库。

**Comment by allenymt** [comment]
blackList 里加上包名排掉

**Comment by allenymt** [comment]
#29 已修复
