### ISSUE TITLE
运行demo都没有拦截到获取androidid的日志

### ISSUE THREAD

**Issue by nealqpl** [allenymt/PrivacySentry#37]

**Comment by nealqpl** [comment]
没有报错，excel也导出了但是没有拦截到androidid的事件
![1656402635036](https://user-images.githubusercontent.com/47093759/176124087-d8bdebd2-46ac-45d9-9dff-1f7d1dbd9923.png)

**Comment by allenymt** [comment]
demo里 测试ANDROIDID点了吗

**Comment by allenymt** [comment]
我这无法复现你说的问题

**Comment by allenymt** [comment]
建议自查，或者试试demo

**Comment by nealqpl** [comment]
> 

当时比较急不能用后就用frida做隐私检测了，感谢您的回复
