### ISSUE TITLE
无法下载插件依赖

### ISSUE THREAD

**Issue by zhaobinsir** [allenymt/PrivacySentry#38]
Could not GET 'https://dl.bintray.com/neteaseim/maven/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.7/plugin-sentry-1.0.7.pom'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project

**Comment by allenymt** [comment]
Disable Gradle 'offline mode' and sync project， 挂个梯子，或者开了离线？

**Comment by allenymt** [comment]
maven { url 'https://jitpack.io' }  这个依赖加了没

**Comment by zhaobinsir** [comment]
> maven { url 'https://jitpack.io' } 这个依赖加了没
加了、而且用的都是阿里云代理、没有开AS离线

**Comment by allenymt** [comment]
你的电脑有没有挂什么特殊代理呢？ 或者公司内网拦截了什么。 一般挂个梯子就行了

**Comment by zhaobinsir** [comment]
> 你的电脑有没有挂什么特殊代理呢？ 或者公司内网拦截了什么。 一般挂个梯子就行了

我试试看

**Comment by zhaobinsir** [comment]
> 你的电脑有没有挂什么特殊代理呢？ 或者公司内网拦截了什么。 一般挂个梯子就行了

梯子搭了、其他依赖可以下载、但是插件无法下载 502错误

**Comment by allenymt** [comment]
要在项目里重试，issue里的地址是不对的，明显是jietpack没拉到从其他仓库拉了

**Comment by allenymt** [comment]
demo也不行？

**Comment by zhaobinsir** [comment]
demo 没有试、我试试

**Comment by zhaobinsir** [comment]
> demo也不行？

找到问题了、因为我们工程加了  maven { url "https://dl.bintray.com/neteaseim/maven" } 这个仓库、 只要加入就会导致 classpath 'com.github.allenymt.PrivacySentry:plugin-sentry:1.0.7' 无法下载、一直502

**Comment by zhaobinsir** [comment]
maven { url 'https://jitpack.io' }  这个库不能在 maven { url "https://dl.bintray.com/neteaseim/maven" } 下面、裂开了，感谢作者的回复

**Comment by LiWeiQiangAndroid** [comment]
jitpack.io 设置了，另外一些又依赖不了，鱼和熊掌不可兼得啊，这库能上传到别的仓库么，我相信别人也遇到这样的情况了，
