### ISSUE TITLE
Could not find com.github.allenymt.PrivacySentry:hook-sentry:1.0.7.

### ISSUE THREAD

**Issue by lingbaeryi-strong** [allenymt/PrivacySentry#40]
Could not find com.github.allenymt.PrivacySentry:hook-sentry:1.0.7.

**Comment by AbnerPing** [comment]
同样问题，Could not find com.github.allenymt.PrivacySentry:hook-sentry:1.0.8。

**Comment by allenymt** [comment]
已经更新
