### ISSUE TITLE
...没看明白怎么用的...

### ISSUE THREAD

**Issue by OhPeterPan** [allenymt/PrivacySentry#44]
大佬，我们现在需求是需要把三方sdk中获取androidid的方法进行拦截，不能调用官方提供的方法，使用我们本地保存的android，这个框架能实现吗？

**Comment by allenymt** [comment]
支持的，针对android这种不可变字段，单进程内默认只会让读取一次，之后都是走缓存。
引入这个库后，业务方不需要处理

**Comment by OhPeterPan** [comment]
> 支持的，针对android这种不可变字段，单进程内默认只会让读取一次，之后都是走缓存。 引入这个库后，业务方不需要处理

是调用这个库里面生成的方法吗？

**Comment by allenymt** [comment]
按Readme里配置下，然后编译打包就行

**Comment by allenymt** [comment]
库内部都处理好的

**Comment by OhPeterPan** [comment]
好的，多谢~~
