### ISSUE TITLE
自定义添加拦截内容

### ISSUE THREAD

**Issue by Chuckkk** [allenymt/PrivacySentry#5]
请问自定义添加拦截内容，是否只需要改动 base 模块下的 HookMethodManager 类所持有的 resultList 成员变量？
比如我想检测移动安全联盟SDK获取OAID等参数，是否在此类中添加以下代码：

`resultList.add(

    HookMethodItem(

        "com/bun/miitmdid/interfaces/IdSupplier",

        "getOAID",

        "()Ljava/lang/String;",

        "移动安全联盟-getOAID"

    )
)`
其对应的java代码为以下，我只 hook 回调中的 idSupplier.getOAID() ：

`MdidSdkHelper.InitSdk(context, true, new IIdentifierListener() {

    @Override

    public void OnSupport(boolean isSupport, IdSupplier idSupplier) {

        Log.d(TAG, "getOAID = " + idSupplier.getOAID());

    }
});`

**Comment by allenymt** [comment]
下个版本马上会发布，支持外部注解的方式注入拦截函数和方法

**Comment by allenymt** [comment]
主分支已更新，支持自定义配置拦截
