### ISSUE TITLE
白名单问题

### ISSUE THREAD

**Issue by Demo-H** [allenymt/PrivacySentry#50]
部分jar会进行SHA1校验，需要添加到白名单。
但添加白名单不生效，不知道需要如何触发才生效，中间生效过一次，但不知道是什么条件触发了配置生效了

**Comment by allenymt** [comment]
包名配置到blackList不行吗

**Comment by Demo-H** [comment]
嗯，是第三方jar的路径名。配置了没有生效

**Comment by allenymt** [comment]
试下 1.2.1 #36 #29
