### ISSUE TITLE
如果没有用到这些依赖的化，能否移除掉呢？

### ISSUE THREAD

**Issue by ve3344** [allenymt/PrivacySentry#53]
如果没有用到这些依赖的化，能否移除掉呢？
implementation 'androidx.core:core-ktx:1.3.2'
implementation 'androidx.appcompat:appcompat:1.3.1'
implementation 'com.google.android.material:material:1.4.0'

**Comment by allenymt** [comment]
core-ktx 这个移除不了，
其他两个已经移除，参考1.0.9版本
