### ISSUE TITLE
有没有办法可以配置debug运行的时候此库不参与编译

### ISSUE THREAD

**Issue by J1aDong** [allenymt/PrivacySentry#55]
debug运行的时候每次修改代码重新运行起来都好久，或者有什么其他的办法提高debug模式下的重新运行的速度

**Comment by allenymt** [comment]
if (project.ext.openPrivacy) {
    apply plugin: 'privacy-sentry-plugin'
    privacy {
        blackList = []
    }
}

自己加个开关判断下，openPrivacy 根据模式是否开启

**Comment by J1aDong** [comment]
Thx

**Comment by allenymt** [comment]
1.2.2
