### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by levistopfun** [allenymt/PrivacySentry#57]
A problem occurred configuring root project 'proj.android-studio'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.allenymt.PrivacySentry:plugin-sentry:1.0.9.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.9/plugin-sentry-1.0.9.pom
       - https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.9/plugin-sentry-1.0.9.pom
       - https://repo.maven.apache.org/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.0.9/plugin-sentry-1.0.9.pom
     Required by:
         project :

不好意思，对Android不是很熟，按照提示导入，会报这个错误，不知道是不是应为库下载不下来，求教一下大佬

**Comment by allenymt** [comment]
1. 在根目录的build.gralde下添加
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
	
	buildscript {
	     dependencies {
	         // 添加插件依赖
	         classpath 'com.github.allenymt.PrivacySentry:plugin-sentry:1.0.9'
	     }
	}

**Comment by wustzhy** [comment]
[PrivacySentry 集成文档](https://github.com/allenymt/PrivacySentry) 少写了一步。。。

还 需要在 在根目录的build.gralde文件 `buildscript {  repositories { `下 添加 `maven { url 'https://jitpack.io' }`
