### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by langxing** [allenymt/PrivacySentry#6]
Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'.
> org.gradle.util.GFileUtils.deleteFileQuietly(Ljava/io/File;)Z

**Comment by EHG613** [comment]
+1

**Comment by allenymt** [comment]
agp版本多少

**Comment by EHG613** [comment]
6.9，插件 4.2.2

**Comment by zhengtingguang** [comment]
这个报错有办法解决吗

**Comment by allenymt** [comment]
最新版本 1.0.2 ，已解决
