### ISSUE TITLE
如何Hook已经存在的方法

### ISSUE THREAD

**Issue by OhPeterPan** [allenymt/PrivacySentry#65]
Lcom/yl/lib/privacy_proxy/ProxyProxyField 这个aar在privacy-proxy里面，您的文档里面说可以不用依赖
 //如果不想使用库中本身的代理方法，可以不引入这个aar，自己实现
  implementation "com.github.allenymt.PrivacySentry:privacy-proxy:$privacyVersion"
但是不依赖又会报错，我现在想实现自己的getString hook，不使用您定义的hook方法，应该如何实现？？

**Comment by allenymt** [comment]
参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt

都正常依赖就行，如果你自己有配置方法，或优先走你的配置方法

**Comment by OhPeterPan** [comment]
> 参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt
> 
> 都正常依赖就行，如果你自己有配置方法，会优先走你的配置方法

是不是没办法绕过您写的hook方法？

**Comment by allenymt** [comment]
> > 参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt
> > 都正常依赖就行，如果你自己有配置方法，会优先走你的配置方法
> 
> 是不是没办法绕过您写的hook方法？

不想用我内置的hook方法吗？

**Comment by OhPeterPan** [comment]
> > > 参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt
> > > 都正常依赖就行，如果你自己有配置方法，会优先走你的配置方法
> > 
> > 
> > 是不是没办法绕过您写的hook方法？
> 
> 不想用我内置的hook方法吗？

对，目前想用自己的实现替代您写的方法

**Comment by allenymt** [comment]
> > > > 参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt
> > > > 都正常依赖就行，如果你自己有配置方法，会优先走你的配置方法
> > > 
> > > 
> > > 是不是没办法绕过您写的hook方法？
> > 
> > 
> > 不想用我内置的hook方法吗？
> 
> 对，目前想用自己的实现替代您写的方法

升级到1.1.0，privacy-proxy可以不引入了

**Comment by OhPeterPan** [comment]
> > > > > 参考这个类https://github.com/allenymt/PrivacySentry/blob/main/app/src/main/java/com/yl/lib/privacysentry/PrivacyProxySelfTest.kt
> > > > > 都正常依赖就行，如果你自己有配置方法，会优先走你的配置方法
> > > > 
> > > > 
> > > > 是不是没办法绕过您写的hook方法？
> > > 
> > > 
> > > 不想用我内置的hook方法吗？
> > 
> > 
> > 对，目前想用自己的实现替代您写的方法
> 
> 升级到1.1.0，privacy-proxy可以不引入了

给力 👍🏻

**Comment by alen252** [comment]
我也是用的1.0.9 不依赖privacy-proxy会报错

**Comment by allenymt** [comment]
没问题，我关了
