### ISSUE TITLE
能添加一个开关，按需进行编译期替换吗？

### ISSUE THREAD

**Issue by chinnsenn** [allenymt/PrivacySentry#67]
引入这个库后，每次编译都要好久，而且有时改动代码后，如果热编译会不生效，要 clean 一下。希望可以平时开发时，插件不工作，等待需求开发完后，手动打开，进行编译期替换。

**Comment by chinnsenn** [comment]
与 #55 相同

**Comment by chinnsenn** [comment]
与 https://github.com/allenymt/PrivacySentry/issues/55 相同

**Comment by allenymt** [comment]
1.2.2
