### ISSUE TITLE
如果项目中用到了AspectJ，引入你这个库只会，AspectJ的切面都会失效

### ISSUE THREAD

**Issue by alen252** [allenymt/PrivacySentry#68]
如果项目中用到了AspectJ，引入你这个库只会，AspectJ的切面都会失效。
不知道是不是ASM影响到啊了AspectJ，作者清楚吗？

**Comment by allenymt** [comment]
你项目里有依赖其他asm的插件吗？ 这个我还真没试过

**Comment by alen252** [comment]
有依赖了其他ASM的插件，是我自己写的一个插件

**Comment by alen252** [comment]
证实是因为你这个库用到了kotlin，引入kotlin后我的AspectJ失效，需要调整AspectJ的配置
