### ISSUE TITLE
部分sdk hook不到

### ISSUE THREAD

**Issue by terry-thz** [allenymt/PrivacySentry#69]
在获取设备的android_id的时，在验证过程中大部分sdk及应用调用都可以hook到Settings.Secure.getString方法。但是有一个穿山甲的广告sdk无法hook到，穿山甲的sdk的通过epic框架分析堆栈也是调用的Settings.Secure.getString方法。但是PirvacySentry框架无法hook到。而其他的sdk都可以正常的hook到。可能是什么原因导致？

**Comment by allenymt** [comment]
代码是动态加载的

**Comment by terry-thz** [comment]
> 代码是动态加载的

有办法解决么？

**Comment by allenymt** [comment]
这种情况没办法，要不上epic这种动态hook的框架，要不找他们SDK

**Comment by terry-thz** [comment]
> 这种情况没办法，要不上epic这种动态hook的框架，要不找他们SDK

嗯。谢谢。EPIC动态框架，ROM版本适配问题相对比较复杂。有没有更简单的，针对性的，比如就是拦截androidid或者imei

**Comment by allenymt** [comment]
应该没有，可能是我不知道。。  线上动态hook风险还是蛮大的。  
SDK也会被风险通报的，一般现在专业的SDK应该都改过了，你问问看有没有新版本

**Comment by terry-thz** [comment]
好的，谢谢。
