### ISSUE TITLE
输出内容可以添加其他的一些信息吗

### ISSUE THREAD

**Issue by zhengtingguang** [allenymt/PrivacySentry#7]
如 调用敏感方法的包名、类名、方法名，可以更好排查哪些第三方SDK在收集信息****，感谢作者

**Comment by allenymt** [comment]
调用堆栈都有的吧

**Comment by zhengtingguang** [comment]
![image](https://user-images.githubusercontent.com/14228431/150298738-ad17a07a-0225-4722-b832-c6d8bfacbe1c.png)
抱歉，xls格式问题，堆栈没有展示完整没看到，感谢感谢

**Comment by zhengtingguang** [comment]
resolved
