### ISSUE TITLE
onResultCallBack没有回调，文件也没生成(解决了，是我其他类删除了）

### ISSUE THREAD

**Issue by WellandLiang** [allenymt/PrivacySentry#70]
onResultCallBack没有回调 文件也没生成
![image](https://user-images.githubusercontent.com/88756458/188261271-4d952b39-ed22-4c2a-b660-a42562f9d727.png)
![image](https://user-images.githubusercontent.com/88756458/188261281-ae54ef07-c002-4024-8adc-ad66198eaec3.png)
哪里出错了

**Comment by allenymt** [comment]
我看下

**Comment by Renwq** [comment]
集成完后 >clean project>卸载手机原有的app>运行安装>跑一下HOOK的方法>adb pull /storage/emulated/0/Android/data/你的包名/files/privacy/configResultFileName()方法配置的名称+.xls

我的开始也没有输出，最后这个步骤就成功了

**Comment by wustzhy** [comment]
运行后，控制台会打印正确的地址
```
E/PrivacyOfficer: 导出Excel success file : /storage/emulated/0/Android/data/com.xxx/files/privacy/buyer_privacy.xls
```
adb pull 接上这个正确的地址，就OK了
