### ISSUE TITLE
app运行起来之后的非法隐私数据采集能hook吗？

### ISSUE THREAD

**Issue by OhPeterPan** [allenymt/PrivacySentry#73]
现在项目集成一个sdk是app运行起来以后才把getAndroidId的代码给下载到本地，好像会导致hook失效？对于这种方式该如何hook？

**Comment by OhPeterPan** [comment]
现在项目集成一个sdk是app运行起来以后才把getAndroidId的代码给下载到本地，好像会导致hook失效？对于这种方式该如何hook？

**Comment by allenymt** [comment]
runtimg用epic检测，线上的话暂时没什么好办法，直接找sdk吧，从源头解决

**Comment by OhPeterPan** [comment]
> runtimg用epic检测，线上的话暂时没什么好办法，直接找sdk吧，从源头解决

哎，epic也在使用，兼容性太差了，很多机型都是直接闪退

**Comment by allenymt** [comment]
epic只能线下检测用用啊
