### ISSUE TITLE
自定义hook问题

### ISSUE THREAD

**Issue by burst3166** [allenymt/PrivacySentry#74]
作者，你好，我只想拦截一个方法，代码如下
@Keep
open class PrivacyProxyCall {

    // kotlin里实际解析的是这个PrivacyProxyCall$Proxy 内部类
    @PrivacyClassProxy
    @Keep
    object Proxy {
        var objectAndroidIdLock = Object()
        @PrivacyMethodProxy(
                originalClass = Settings.Secure::class,
                originalMethod = "getString",
                originalOpcode = MethodInvokeOpcode.INVOKESTATIC
        )
        @JvmStatic
        fun getString(contentResolver: ContentResolver?, type: String?): String? {
            var key = "Secure-getString-$type"
            if (!"android_id".equals(type)) {
                return Settings.Secure.getString(
                        contentResolver,
                        type
                )
            }
            if (PrivacySentry.Privacy.getBuilder()?.isVisitorModel() == true) {
                doFilePrinter(
                        "getString",
                        "系统信息",
                        args = type,
                        bVisitorModel = true
                )
                return ""
            }
            synchronized(objectAndroidIdLock) {
                var hasValue = PrivacyProxyUtil.Util.hasReadStaticParam(key)
                if (!hasValue) {
                    doFilePrinter("getString", "系统信息", args = type)
                    var result = ""
                    try {
                        result = Settings.Secure.getString(
                                contentResolver,
                                type
                        )
                    } catch (e: Throwable) {
                        //不管有没有申请，部分机子直接跑异常
                        throw e
                    } finally {
                        PrivacyProxyUtil.Util.putCacheStaticParam(result ?: "", key)
                    }
                    return result
                } else {
                    doFilePrinter(
                            "getString",
                            "系统信息",
                            args = type,
                            bCache = true
                    )
                    return PrivacyProxyUtil.Util.getCacheStaticParam("", key)
                }
            }
        }

       

    }
}

但是编译后，发现仍然替换了大多数方法，同时还会崩溃
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/col/xx/xx/xx/PrivacyProxyResolver$Proxy;
E/AndroidRuntime(22187): 	at com.sensorsdata.analytics.android.sdk.data.adapter.EventDataOperation.queryData(EventDataOperation.java:73)

本来以为是编译缓存问题，但是执行flutter clean后，还是一样的结果。 是不支持只拦截某个类的某个方法吗？

**Comment by burst3166** [comment]
使用的是1.1.0版本，没有导入privacy-proxy包

**Comment by allenymt** [comment]
试了下 没问题的，主分支我提交了，你可以试试看

**Comment by allenymt** [comment]
最好用./gradlew clean

**Comment by burst3166** [comment]
./gradlew clean 和 flutter clean都试了 ，还是一样的错误，感觉就像缓存没清掉一样。
而且replace.json还是显示替换了常见的隐私api

**Comment by allenymt** [comment]
看下依赖树，privacy-proxy是不是又依赖进去了
