### ISSUE TITLE
buyer_privacy.xls与{包名}/channel_buyer_privacy区别

### ISSUE THREAD

**Issue by kkmike999** [allenymt/PrivacySentry#76]
**buyer_privacy.xls**与**{包名}/channel_buyer_privacy**，有什么区别吗？一个很少信息，一个很多信息

**Comment by allenymt** [comment]
buyer_privacy.xls 是你主进程的
**{包名}/channel_buyer_privacy** 是子进程的，子进程的信息也要关注下，部分SDK也会读取敏感字段
