### ISSUE TITLE
不知道为啥我这边写就是没有Hook住，版本用的是1.0.7，看之前有修复的这个的

### ISSUE THREAD

**Issue by GlutinousRice** [allenymt/PrivacySentry#78]
public static String getUniqueId(Context context) {
        @SuppressLint("HardwareIds") String androidID = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID);
        String id = androidID + Build.SERIAL;
        try {
            return toMD5(id);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return id;
        }
    }

**Comment by allenymt** [comment]
反编译看看，方法替换了吗
