### ISSUE TITLE
 fun getRecentTasks( 没有加JvmStatic注解 是不是漏了？

### ISSUE THREAD

**Issue by alen252** [allenymt/PrivacySentry#83]
fun getRecentTasks(
没有加JvmStatic注解 是不是漏了？

**Comment by allenymt** [comment]
有啊，看错了吧

**Comment by alen252** [comment]
![image](https://user-images.githubusercontent.com/13713307/198517186-9e99fdf2-f90b-4a8f-83c2-070af1e306b9.png)
写在这上面是一样的？

**Comment by allenymt** [comment]
当然一样的
