### ISSUE TITLE
资源文件是不是找不到了

### ISSUE THREAD

**Issue by zhangspace** [allenymt/PrivacySentry#86]
访问路径 https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.1.0/plugin-sentry-1.1.0.pom
提示
{
"errors" : [ {
"status" : 404,
"message" : "Could not find resource"
} ]
}

**Comment by runforprogram** [comment]
> 访问路径 https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.1.0/plugin-sentry-1.1.0.pom 提示 { "errors" : [ { "status" : 404, "message" : "Could not find resource" } ] }

应该在jetpack.io上面，jcenter不是都关了吗？
