### ISSUE TITLE
没有拦截到其他方法，只有隐私协议

### ISSUE THREAD

**Issue by FunBucket-lee** [allenymt/PrivacySentry#87]
没有拦截到其他方法，只有隐私协议
![9878e4cf5f6b6a689934ff1545a7a59](https://user-images.githubusercontent.com/61619009/199178451-df3074d2-e188-4a63-bb8e-68d4970fffcf.jpg)

**Comment by FunBucket-lee** [comment]
不过我是写flutter，在安卓原生初始化
![Uploading 226511ab071a15304469cc2bc65c19e.jpg…]()

**Comment by FunBucket-lee** [comment]
日志只要是这些
![Uploading 41fc108e2535a8143118f109d39cb40.jpg…]()

**Comment by allenymt** [comment]
反编译看看代码hook成功没

**Comment by zhangspace** [comment]
楼主有解决么，我也是

**Comment by FunBucket-lee** [comment]
咋反编译看apk hook是否成功，新手安卓不太懂
