### ISSUE TITLE
关闭了日志文件输出，还是会被检测出来读写相关的权限，是为啥

### ISSUE THREAD

**Issue by ChangWeiBa** [allenymt/PrivacySentry#88]
![微信截图_20221102134451](https://user-images.githubusercontent.com/20971864/199408127-b89a65a8-baeb-42f9-a90f-1804929e5e0c.png)
![微信截图_20221102134417](https://user-images.githubusercontent.com/20971864/199408141-0b7aa417-3fde-460b-95ca-75e804951767.png)
这是初始化代码和测试给出的检测相关的堆栈信息，用的版本是1.1.0

我看你6天前有提交一个优化日志逻辑的commit，是解决这个问题的吗？如果是的话能更新一下包吗

**Comment by allenymt** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/8003195/199460376-99df4713-d119-404a-890e-7da34df233f3.png">
这三个堆栈是什么，对照mapping文件看看

**Comment by ChangWeiBa** [comment]
> <img alt="image" width="265" src="https://user-images.githubusercontent.com/8003195/199460376-99df4713-d119-404a-890e-7da34df233f3.png">
> 
> 这三个堆栈是什么，对照mapping文件看看

这个咋看啊。 我用我自己的mapping查看，还是看不到这个

**Comment by allenymt** [comment]
1.2.2
