### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by RevivalDev** [allenymt/PrivacySentry#89]
您好，我按照文档说明，在项目中添加之后，进行同步的时候报错了，说无法找到文件，报错内容
“Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.allenymt.PrivacySentry:plugin-sentry:1.2.0.
     Searched in the following locations:
       - https://jitpack.io/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://maven.aliyun.com/repository/public/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://maven.aliyun.com/repository/central/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://maven.aliyun.com/repository/google/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://repo.maven.apache.org/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://developer.huawei.com/repo/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom
       - https://jcenter.bintray.com/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom”

然后我直接访问“https://jitpack.io/com/github/allenymt/PrivacySentry/plugin-sentry/1.2.0/plugin-sentry-1.2.0.pom”，页面显示“Build failed. See the log at jitpack.io”

**Comment by RevivalDev** [comment]
版本降低到 1.1.0 解决这个问题

**Comment by allenymt** [comment]
是1.2.1 ，文档忘记更新了。。
