### ISSUE TITLE
怎么阅读生成的文件

### ISSUE THREAD

**Issue by supercwn** [allenymt/PrivacySentry#92]
生成的nuyer_privacy.xls文件，怎么阅读在未同意隐私权限的前调用了违规的隐私代码

**Comment by allenymt** [comment]
Readme里有这一步：
在隐私协议确认的时候调用，这一步非常重要！，一定要加
    kotlin:PrivacySentry.Privacy.updatePrivacyShow()
    java:PrivacySentry.Privacy.INSTANCE.updatePrivacyShow();

调用后，会把这一步写到文件里，这样就知道是不是在同意隐私权限前调用了，建议先跑跑demo吧
